# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: export DATABASE_URL=${{ secrets.DATABASE_URL }}
      - run: yarn prisma migrate dev
      - run: yarn prisma db seed
      - run: yarn prisma generate
      - run: yarn build

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: '.git/, /node_modules/'
          SCRIPT_BEFORE: |
            source ~/.nvm/nvm.sh; npm install pm2 -g
            source ~/.nvm/nvm.sh; npm install yarn -g
          SCRIPT_AFTER: |
            source ~/.nvm/nvm.sh; cd deploy && yarn;
            pm2 delete biblioteca
            pm2 start ~/deploy/dist/server.js --name="biblioteca"  --env=../../env
